#!/bin/bash

repeat() { while :; sleep 2; do $@ && return; done }

# setup configuration
cp /root/config.toml /root/.lotus/config.toml

while getopts sdc option
do
    case "${option}" in
        s) SYNC=true;;
        d) DAEMON=true;;
        i) IMPORT=true;;
    esac
done
    
if [ "$DAEMON" == true ] ; then
    echo "Starting daemon"
    # Start the daemon process
    lotus daemon
fi

if [ "$SYNC" == true ] ; then
    echo "Starting sync wait"
    # Start the daemon process and put it in the background
    lotus daemon &
    # Run the sync process until it dies
    repeat lotus sync wait
fi


if [ "$IMPORT" == true ] ; then
	# This only works for mainnet. See the following:
	# https://docs.filecoin.io/get-started/lotus/chain/#syncing-from-a-full-snapshot-mainnet
	lotus daemon --import-snapshot https://fil-chain-snapshots-fallback.s3.amazonaws.com/mainnet/minimal_finality_stateroots_latest.car --halt-after-import
fi
